version: '2'
services:
  gateway_test:    
    image: aksenchyk/fm-200loc:build
    environment:
      # codecov.io requires this variables
      - CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM  
      - CIRCLECI=$CIRCLECI
      - CIRCLE_BUILD_NUM = $CIRCLE_BUILD_NUM
      - CIRCLE_NODE_INDEX=$CIRCLE_NODE_INDEX
      - CIRCLE_SHA1=$CIRCLE_SHA1
      - CIRCLE_BRANCH=$CIRCLE_BRANCH
      - CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER
      - CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME
      - CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME
      - CIRCLE_ARTIFACTS=$CIRCLE_ARTIFACTS
    env_file:
      - ./test_.env
    depends_on:      
      - test_db    
    entrypoint: ./wait-for-it.sh test_db:27017 -s -- npm run test-cov    
  test_db:    
    image: mongo:latest 